### ISSUE TITLE
Multiverse incompatibility

### ISSUE THREAD

**Issue by Aezwen** [lesteenman/StargateCraft#1]
I have a setup of two multiverse worlds.

I have one multiverse world set to Creative mode using /mvm set mode creative and another multiverse world set to Survival mode using /mvm set mode survival

I have the inventory of the Creative world in a different group from the inventory of the Survival world.

When I use /mvtp to teleport to a world, the inventory switches to the inventory group I've selected for the world. When I use /mvtp the game mode switches to the game mode I've selected for the world.

But when I use SGCraft-1.3.0-mc1.7.2's star gate to travel from one world to the other, the inventory AND the game mode don't switch over to what I've selected for them, they only switch over if I use /mvtp.

Now anyone can use the star gate to go into Creative mode in the world that I want to be game mode Survival.

I posted about this incompatibility on Multiverse and got this response:

TWSSYesterday:
I take it SGCraft is a mod? Make an issue on github if it's an incompatible :)

**Comment by lesteenman** [comment]
Considering that this mod was never finished, I assume that you mean the other Stargate mod, which only adds dimension portals. This was supposed to be a mod that added a lot of stargate, the series stuff.
